# Generated by Django 4.2.11 on 2024-04-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(help_text="Date of the performance record."),
                ),
                (
                    "on_time_delivery_rate",
                    models.FloatField(
                        help_text="Historical record of the on-time delivery rate."
                    ),
                ),
                (
                    "quality_rating_avg",
                    models.FloatField(
                        help_text="Historical record of the quality rating average."
                    ),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        help_text="Historical record of the average response time."
                    ),
                ),
                (
                    "fulfillment_rate",
                    models.FloatField(
                        help_text="Historical record of the fulfilment rate."
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendors.vendor"
                    ),
                ),
            ],
        ),
    ]
