# Generated by Django 4.2.11 on 2024-04-30 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        help_text="Unique number identifying the PO.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when the order was placed.",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        help_text="Expected or actual delivery date of the order."
                    ),
                ),
                ("items", models.JSONField(help_text="Details of items ordered.")),
                (
                    "quantity",
                    models.IntegerField(help_text="Total quantity of items in the PO."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        help_text="Current status of the PO",
                        max_length=20,
                    ),
                ),
                (
                    "quality_rating",
                    models.FloatField(
                        help_text="Rating given to the vendor for this PO.", null=True
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the PO was issued to the vendor.",
                    ),
                ),
                (
                    "acknowledgment_date",
                    models.DateTimeField(
                        help_text="Timestamp when the vendor acknowledged the PO.",
                        null=True,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendors.vendor"
                    ),
                ),
            ],
        ),
    ]
